#!/bin/sh

# Find the bluetooth keyboard
HID_NAME="ThinkPad Compact Bluetooth Keyboard with TrackPoint"
HIDRAWS=$(grep -l "HID_NAME=$HID_NAME" /sys/class/hidraw/hidraw*/device/uevent | grep -oE 'hidraw[0-9]+')
if [ -z "$HIDRAWS" ]; then
    echo "No keyboard found!"
    exit 1
fi

# Do command for all keyboards attached
for HIDRAW in $HIDRAWS; do
    if [ "$1" = "--fn-lock-disable" ]; then
        echo Disabling Fn lock for /dev/$HIDRAW...
        /bin/echo -ne "\x18\x05\x00" | dd of=/dev/$HIDRAW 2>/dev/null
    elif [ "$1" = "--fn-lock-enable" ]; then
        echo Enabling Fn lock for /dev/$HIDRAW...
        /bin/echo -ne "\x18\x05\x01" | dd of=/dev/$HIDRAW 2>/dev/null
    else
        echo Nothing to do.
    fi
done
